version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rightchain-frontend
    environment:
        NODE_ENV: production
        PORT: 50000
    ports:
      - "50000:3000"
    restart: always